# Generated by Django 5.0.6 on 2026-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parsedresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
