# Generated by Django 5.0.6 on 2026-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_id_alter_job_id_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
